apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: tenant-a-team-01
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'team-01'
  source:
    repoURL: git@github.com:Romanecek/kb-poc-argo-app1.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: in-cluster
    namespace: tenant-a-team-01
  project: 'team-01'
# project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

