apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: tenant-a
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    directory:
      include:  'appset.yaml'
    repoURL: git@github.com:Romanecek/kb-poc-argo-app1.git
    targetRevision: main
    path: .
  destination:
    name: in-cluster
    namespace: tenant-a
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

