apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1
  namespace: tenant-a
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:Romanecek/kb-poc-argo-app1.git
        revision: main
        directories:
          - path: '*'
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: git@github.com:Romanecek/kb-poc-argo-app1.git
        targetRevision: main
        path: '{{.path.basename}}'
        helm:
          valueFiles:
            - ../values.yaml
      destination:
        name: cluster-01
        namespace: app1
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true