apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: tenant-a
  labels:
    app.kubernetes.io/part-of: app1
    app.kubernetes.io/app-name: app1
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app1
    name: cluster-01
  project: default
  source:
    path: nginx
    repoURL: git@github.com:Romanecek/kb-poc-argo-app1.git
    targetRevision: main
    helm:
      valueFiles:
      - ../values.yaml
      releaseName: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true